config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :shops, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  def index
    if params[:place_id]
      @place = GooglePlaceClient.new.details(params[:place_id])["result"]
    elsif params[:address] && params[:nature]
      query = "#{params[:nature]} in: #{params[:address]}"
      @places = GooglePlaceClient.new.find(query)['candidates']
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FindCie</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shops/index.html.erb
<h1>Recherchez une enseigne:</h1>
<%= form_tag shops_path, method: :get do %>
  <label for="address">Adresse</label>
  <%= text_field_tag :address %>
  <label for="nature">Nature</label>
  <%= text_field_tag :nature %>
  <%= button_tag 'Chercher', type: 'submit' %>
<% end %>

<% if @places %>
  <ul>
    <% @places.each do |place| %>
      <li>
        <%= place['name'] %>, <%= place['formatted_address'] %>
        <%= form_tag shops_path, method: :get do %>
          <div style="display:none;">
            <%= text_field_tag :place_id, place['place_id'] %>
          </div>
          <%= button_tag 'Contact', type: 'submit' %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <%= link_to 'Nouvelle recherche', shops_path %>
<% end %>

<% if @place %>
  <%= @place['name'] %> <%= @place['formatted_phone_number'] %>
  <%= link_to 'Nouvelle recherche', shops_path %>
<% end %>